spring:
  application:
    name: incident-response-orchestrator


  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/incident_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

  # Mail Configuration
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 6033da39dc0333
    password: ffbc50a7bda518
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: mySuperSecretDevelopmentKeyThatIsVeryLong12345!
  expiration: 86400000


  servlet:
    multipart:
      max-file-size= 10MB
      max-request-size= 10MB
